export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  RECEPTIONS: '/receptions',
  SHABBAT: '/shabbat',
  CHECKOUT: '/checkout',
  CHECKOUT_SUCCESS: '/checkout/success',
  CHECKOUT_CANCEL: '/checkout/cancel',
  GALLERY: '/gallery',
  FAQ: '/faq',
  CONTACT: '/contact',
  ADMIN: '/admin',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_QUOTES: '/admin/quotes',
  ADMIN_MEDIA: '/admin/media',
  ADMIN_FAQ: '/admin/faq',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_MESSAGES: '/admin/messages',
  ADMIN_CUSTOMERS: '/admin/customers',
  ADMIN_LOGIN: '/admin/login',
} as const;
